# Generated by Django 5.2.8 on 2025-11-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0005_comentario_autor_convidado_alter_comentario_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='endereco',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
